services:
  user-service:
    env_file:
      - .env
    image: 299029452437.dkr.ecr.us-east-1.amazonaws.com/user-service:latest
    ports:
      - "8001:80"

  order-service:
    env_file:
      - .env
    image: 299029452437.dkr.ecr.us-east-1.amazonaws.com/order-service:latest
    ports:
      - "8002:80"

  activity-service:
    image: 299029452437.dkr.ecr.us-east-1.amazonaws.com/activity-service:latest
    ports:
      - "8003:80"
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/27017"]
      interval: 10s
      timeout: 5s
      retries: 5

  
