name: Build and Deploy

on:
  push:
    branches:
      - ecs

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 299029452437.dkr.ecr.us-east-1.amazonaws.com

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS \
          --password-stdin $ECR_REGISTRY
      
      - name: Build user-service
        run: |
          docker build -t orders-platform-user-service:latest ./user-service
          docker tag orders-platform-user-service:latest $ECR_REGISTRY/user-service:latest
      
      - name: Build order-service
        run: |
          docker build -t orders-platform-order-service:latest ./order-service
          docker tag orders-platform-order-service:latest $ECR_REGISTRY/order-service:latest
        
      - name: Build activity-service
        run: |
          docker build -t orders-platform-activity-service:latest ./activity-service
          docker tag orders-platform-activity-service:latest $ECR_REGISTRY/activity-service:latest

      - name: Push imagesto ECR
        run: |
          docker push $ECR_REGISTRY/user-service:latest
          docker push $ECR_REGISTRY/order-service:latest
          docker push $ECR_REGISTRY/activity-service:latest

  deploy-ecs:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Run DB initialization scripts
        run: |
          echo "Running DB setup (create_tables)..."

          SERVICES="user-service order-service"

          for service in $SERVICES; do
            echo "Running DB init for $service"

            docker run --rm \
              -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
              $ECR_REGISTRY/$service:latest \
              python -m scripts.init_db

          done
      
      - name: Detect changed task definitions
        id: changes
        run: |
          set -e

          BASE_SHA="${{ github.event.before }}"
          HEAD_SHA="${{ github.sha }}"

          # Fix edge case: initial commit / invalid SHA
          if [ "$BASE_SHA" = "0000000000000000000000000000000000000000" ] || [ -z "$BASE_SHA" ]; then
            echo "No valid base SHA, treating all task defs as changed"
            FILES=$(find ecs-tasks -name "*.json")
          else
            FILES=$(git diff --name-only $BASE_SHA $HEAD_SHA || true)
            FILES=$(echo "$FILES" | grep '^ecs-tasks/.*\.json$' || true)
          fi

          echo "tasks<<EOF" >> $GITHUB_OUTPUT
          echo "$FILES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Register task definitions and deploy
        if: steps.changes.outputs.tasks != ''
        run: |
          set -e

          for file in ${{ steps.changes.outputs.tasks }}; do
            echo "Processing $file"

            # extract service name from file (ecs-tasks/user-service.json → user-service)
            service=$(basename "$file" .json)

            echo "Service: $service"

            echo "Registering new task definition revision..."
            aws ecs register-task-definition \
              --cli-input-json file://$file

            echo "Checking if ECS service exists..."

            SERVICE_STATUS=$(aws ecs describe-services \
              --cluster $ECS_CLUSTER \
              --services $service \
              --query 'services[0].status' \
              --output text 2>/dev/null || echo "MISSING")

            if [ "$SERVICE_STATUS" = "MISSING" ] || [ "$SERVICE_STATUS" = "INACTIVE" ]; then
              echo "Creating ECS service: $service"

              aws ecs create-service \
                --cluster $ECS_CLUSTER \
                --service-name $service \
                --task-definition $service \
                --desired-count 1 \
                --launch-type EC2
            else
              echo "Updating ECS service: $service"

              aws ecs update-service \
                --cluster $ECS_CLUSTER \
                --service $service \
                --force-new-deployment
            fi

          done